version: '3'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0.17
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: crud
      MYSQL_USER: utku
      MYSQL_PASSWORD: utku5858
      MYSQL_ROOT_PASSWORD: utku5858
    volumes:
        - my-db:/var/lib/mysql
volumes:
  my-db:

